name: build binary

on:
  release:
    types: [published]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: 1.47.0
          target: x86_64-unknown-linux-gnu
          
      - run: rustc --version

      - uses: actions-rs/cargo@v1
        with:
          command: build
          args: --release --features final --target x86_64-unknown-linux-gnu
      - name: export binary
        uses: actions/upload-artifact@v3
        with:
          name: openethereum-${{ env.GITHUB_REF_NAME }}-x86_x64_unknown_gnu
          path: target/x86_64-unknown-linux-gnu/release/openethereum
